---
AllCops:
  TargetRubyVersion: '2.6'
  AllowSymlinksInCacheRootDirectory: true
  NewCops: enable
  Exclude:
    - vendor/bundle/**/*
require:
- rubocop-rake
- rubocop-rspec
Layout/HashAlignment:
  EnforcedHashRocketStyle: table
Layout/LineLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/ParameterLists:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
RSpec/SubjectStub:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/NumericLiterals:
  Enabled: false
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

